#!/bin/bash
set -e
set -u

THIS_SCRIPTS_DIRECTORY=$(realpath $(dirname "$0"))

# Load variables in CONF_FILE
CONF_FILE=$1
source $CONF_FILE

# Assert required variables are loaded
: "$YEAR" "$MONTH" "$WORKINGDIR" "$WGET_OPTIONS"

# Export download settings
export WORKINGDIR=$WORKINGDIR
export WGET_OPTIONS="$WGET_OPTIONS"
export NAME="$NAME"

# Get URL list
URLS=$(YEAR=$YEAR MONTH=$MONTH $(dirname $CONF_FILE)/get_urls.sh)

# Make sure working dir exists
mkdir -p $WORKINGDIR

# Launch download
$THIS_SCRIPTS_DIRECTORY/submit_download - <(echo "$URLS")
